INFO 2025-05-07 04:10:48,408 autoreload Watching for file changes with StatReloader
INFO 2025-05-07 04:10:48,775 environment [ENV] 当前运行环境: development
INFO 2025-05-07 04:10:48,775 environment [ENV] 当前运行环境: development
INFO 2025-05-07 04:11:17,319 autoreload Watching for file changes with StatReloader
INFO 2025-05-07 04:11:17,744 environment [ENV] 当前运行环境: development
INFO 2025-05-07 04:11:17,744 environment [ENV] 当前运行环境: development
INFO 2025-05-07 04:11:35,795 basehttp "GET / HTTP/1.1" 200 41349
INFO 2025-05-07 04:11:35,844 basehttp "GET /static/css/styles.css HTTP/1.1" 200 16268
INFO 2025-05-07 04:11:35,865 basehttp "GET /static/js/scripts.js HTTP/1.1" 200 10773
WARNING 2025-05-07 04:11:51,087 log Not Found: /favicon.ico
WARNING 2025-05-07 04:11:51,088 basehttp "GET /favicon.ico HTTP/1.1" 404 4688
INFO 2025-05-07 04:12:20,113 basehttp - Broken pipe from ('127.0.0.1', 50306)
INFO 2025-05-07 04:20:35,630 basehttp "GET / HTTP/1.1" 200 41355
INFO 2025-05-07 04:20:35,651 basehttp "GET /static/css/styles.css HTTP/1.1" 304 0
INFO 2025-05-07 04:20:35,671 basehttp "GET /static/js/scripts.js HTTP/1.1" 304 0
ERROR 2025-05-07 04:28:04,349 log Internal Server Error: /
Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrischan/Documents/RushRental/pages/views.py", line 38, in home
    return render(request, 'home.html', context)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-07 04:28:04,353 basehttp "GET / HTTP/1.1" 500 197534
ERROR 2025-05-07 04:31:38,793 log Internal Server Error: /
Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrischan/Documents/RushRental/pages/views.py", line 38, in home
    return render(request, 'home.html', context)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-07 04:31:38,795 basehttp "GET / HTTP/1.1" 500 197528
ERROR 2025-05-07 04:31:58,532 log Internal Server Error: /
Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrischan/Documents/RushRental/pages/views.py", line 38, in home
    return render(request, 'home.html', context)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-07 04:31:58,534 basehttp "GET / HTTP/1.1" 500 197528
ERROR 2025-05-07 04:31:59,472 log Internal Server Error: /
Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrischan/Documents/RushRental/pages/views.py", line 38, in home
    return render(request, 'home.html', context)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-07 04:31:59,474 basehttp "GET / HTTP/1.1" 500 197528
ERROR 2025-05-07 04:34:17,212 log Internal Server Error: /
Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrischan/Documents/RushRental/pages/views.py", line 38, in home
    return render(request, 'home.html', context)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-07 04:34:17,214 basehttp "GET / HTTP/1.1" 500 197528
ERROR 2025-05-07 04:34:19,860 log Internal Server Error: /
Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrischan/Documents/RushRental/pages/views.py", line 38, in home
    return render(request, 'home.html', context)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-07 04:34:19,862 basehttp "GET / HTTP/1.1" 500 197528
ERROR 2025-05-07 04:34:20,699 log Internal Server Error: /
Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chrischan/Documents/RushRental/pages/views.py", line 38, in home
    return render(request, 'home.html', context)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrischan/Documents/RushRental/venv/lib/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-07 04:34:20,701 basehttp "GET / HTTP/1.1" 500 197528
INFO 2025-05-07 04:34:42,072 basehttp "GET / HTTP/1.1" 200 42196
INFO 2025-05-07 04:34:42,090 basehttp "GET /static/css/styles.css HTTP/1.1" 304 0
INFO 2025-05-07 04:34:42,091 basehttp "GET /static/images/promotion.jpg HTTP/1.1" 200 36879
INFO 2025-05-07 04:34:42,112 basehttp "GET /static/js/scripts.js HTTP/1.1" 304 0
INFO 2025-05-07 04:36:32,383 basehttp "GET / HTTP/1.1" 200 42196
INFO 2025-05-07 04:36:32,438 basehttp "GET /static/images/promotion.jpg HTTP/1.1" 304 0
INFO 2025-05-16 15:14:54,731 autoreload Watching for file changes with StatReloader
INFO 2025-05-16 15:14:58,152 environment [ENV] 当前运行环境: development
INFO 2025-05-16 15:14:58,152 environment [ENV] 当前运行环境: development
WARNING 2025-05-16 15:15:12,694 base Session data corrupted
INFO 2025-05-16 15:15:14,356 basehttp "GET / HTTP/1.1" 200 38212
WARNING 2025-05-16 15:15:16,772 base Session data corrupted
INFO 2025-05-16 15:15:18,379 basehttp "GET / HTTP/1.1" 200 38260
INFO 2025-05-16 15:15:18,598 basehttp "GET /static/css/styles.css HTTP/1.1" 200 16268
INFO 2025-05-16 15:15:18,599 basehttp "GET /static/images/promotion.jpg HTTP/1.1" 200 36879
INFO 2025-05-16 15:15:18,606 basehttp "GET /static/images/car-placeholder.jpg HTTP/1.1" 200 56241
INFO 2025-05-16 15:15:18,608 basehttp "GET /static/images/logo.png HTTP/1.1" 200 2687817
INFO 2025-05-16 15:15:18,613 basehttp "GET /static/js/scripts.js HTTP/1.1" 200 10773
WARNING 2025-05-16 15:16:53,443 base Session data corrupted
INFO 2025-05-16 15:16:55,079 basehttp "GET / HTTP/1.1" 200 38267
INFO 2025-05-16 15:16:55,138 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 15:18:19,437 base Session data corrupted
INFO 2025-05-16 15:18:21,254 basehttp "GET / HTTP/1.1" 200 38513
INFO 2025-05-16 15:18:21,332 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
INFO 2025-05-16 15:18:21,348 basehttp "GET /static/images/promotion.jpg HTTP/1.1" 304 0
WARNING 2025-05-16 15:19:27,806 base Session data corrupted
INFO 2025-05-16 15:19:29,503 basehttp "GET / HTTP/1.1" 200 37658
INFO 2025-05-16 15:19:29,599 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 15:20:53,106 base Session data corrupted
INFO 2025-05-16 15:20:54,754 basehttp "GET / HTTP/1.1" 200 37623
INFO 2025-05-16 15:20:54,863 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 15:21:04,199 base Session data corrupted
INFO 2025-05-16 15:21:05,923 basehttp "GET / HTTP/1.1" 200 37660
WARNING 2025-05-16 15:21:18,624 base Session data corrupted
INFO 2025-05-16 15:21:20,270 basehttp "GET / HTTP/1.1" 200 37623
WARNING 2025-05-16 15:22:18,033 base Session data corrupted
INFO 2025-05-16 15:22:19,687 basehttp "GET / HTTP/1.1" 200 37669
INFO 2025-05-16 15:22:19,765 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 15:23:26,626 base Session data corrupted
INFO 2025-05-16 15:23:28,274 basehttp "GET / HTTP/1.1" 200 37618
INFO 2025-05-16 15:23:28,389 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 15:23:41,558 base Session data corrupted
INFO 2025-05-16 15:23:43,397 basehttp "GET / HTTP/1.1" 200 37674
WARNING 2025-05-16 15:25:27,132 base Session data corrupted
INFO 2025-05-16 15:25:28,812 basehttp "GET / HTTP/1.1" 200 37632
INFO 2025-05-16 15:25:28,973 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
INFO 2025-05-16 15:41:03,738 autoreload Watching for file changes with StatReloader
INFO 2025-05-16 15:41:06,376 environment [ENV] 当前运行环境: development
INFO 2025-05-16 15:41:06,376 environment [ENV] 当前运行环境: development
INFO 2025-05-16 15:41:19,946 basehttp "GET / HTTP/1.1" 200 37632
INFO 2025-05-16 15:41:20,082 basehttp "GET /static/images/logo.png HTTP/1.1" 200 2687817
INFO 2025-05-16 15:45:46,908 basehttp "GET /cars/ HTTP/1.1" 200 23279
INFO 2025-05-16 15:45:53,768 basehttp "GET / HTTP/1.1" 200 38980
INFO 2025-05-16 15:45:53,838 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
INFO 2025-05-16 15:51:29,547 basehttp "GET / HTTP/1.1" 200 38932
INFO 2025-05-16 15:51:29,684 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
INFO 2025-05-16 15:51:38,459 basehttp "GET /cars/ HTTP/1.1" 200 23279
INFO 2025-05-16 15:51:46,986 basehttp "GET / HTTP/1.1" 200 38963
INFO 2025-05-16 15:53:56,468 basehttp "GET / HTTP/1.1" 200 38947
INFO 2025-05-16 15:53:56,556 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 15:54:46,530 base Session data corrupted
INFO 2025-05-16 15:54:48,238 basehttp "GET / HTTP/1.1" 200 38947
INFO 2025-05-16 15:54:48,469 basehttp "GET /static/css/styles.css HTTP/1.1" 200 16268
INFO 2025-05-16 15:54:48,469 basehttp "GET /static/js/scripts.js HTTP/1.1" 200 10773
INFO 2025-05-16 15:54:48,471 basehttp "GET /static/images/car-placeholder.jpg HTTP/1.1" 200 56241
INFO 2025-05-16 15:54:48,481 basehttp "GET /static/images/logo.png HTTP/1.1" 200 2687817
WARNING 2025-05-16 15:54:51,477 log Not Found: /favicon.ico
WARNING 2025-05-16 15:54:51,478 basehttp "GET /favicon.ico HTTP/1.1" 404 4688
WARNING 2025-05-16 15:56:23,649 base Session data corrupted
INFO 2025-05-16 15:56:25,311 basehttp "GET / HTTP/1.1" 200 38950
INFO 2025-05-16 15:56:25,358 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 15:57:02,240 base Session data corrupted
INFO 2025-05-16 15:57:03,827 basehttp "GET / HTTP/1.1" 200 35299
WARNING 2025-05-16 15:57:31,548 base Session data corrupted
INFO 2025-05-16 15:57:32,105 basehttp "GET /cars/?pickup_location=Brisbane HTTP/1.1" 200 17236
WARNING 2025-05-16 16:00:16,077 base Session data corrupted
INFO 2025-05-16 16:00:17,698 basehttp "GET / HTTP/1.1" 200 35330
INFO 2025-05-16 16:00:17,789 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 16:00:39,613 base Session data corrupted
INFO 2025-05-16 16:00:40,156 basehttp "GET /cars/?pickup_location=Brisbane HTTP/1.1" 200 17245
WARNING 2025-05-16 16:03:20,070 base Session data corrupted
INFO 2025-05-16 16:03:21,695 basehttp "GET / HTTP/1.1" 200 31813
INFO 2025-05-16 16:03:21,767 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 16:03:52,645 base Session data corrupted
INFO 2025-05-16 16:03:54,355 basehttp "GET / HTTP/1.1" 200 31777
WARNING 2025-05-16 16:07:43,017 base Session data corrupted
INFO 2025-05-16 16:07:44,604 basehttp "GET / HTTP/1.1" 200 31766
INFO 2025-05-16 16:07:44,690 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 16:08:25,186 base Session data corrupted
INFO 2025-05-16 16:08:26,815 basehttp "GET / HTTP/1.1" 200 31766
INFO 2025-05-16 16:11:34,209 basehttp "GET / HTTP/1.1" 200 31953
INFO 2025-05-16 16:11:34,270 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
INFO 2025-05-16 16:12:05,167 basehttp "GET /cars/ HTTP/1.1" 200 17426
INFO 2025-05-16 16:12:52,243 basehttp "GET / HTTP/1.1" 200 31878
INFO 2025-05-16 16:14:15,840 basehttp "GET /rental-conditions/ HTTP/1.1" 200 12518
INFO 2025-05-16 16:14:28,270 basehttp "GET / HTTP/1.1" 200 31900
WARNING 2025-05-16 16:24:05,662 base Session data corrupted
INFO 2025-05-16 16:24:07,301 basehttp "GET / HTTP/1.1" 200 34304
INFO 2025-05-16 16:24:07,443 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 16:25:31,189 base Session data corrupted
ERROR 2025-05-16 16:25:31,214 log Internal Server Error: /
Traceback (most recent call last):
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "ep-cold-cherry-a4g2g059.us-east-1.aws.neon.tech" (2600:1f18:240c:544d:621b:957c:81:5e5b), port 5432 failed: ERROR:  You've exceeded the rate limit. Please wait a moment and try again.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/go/src/github.com/RushRental/pages/views.py", line 15, in home
    if featured_vehicles.count() < 4:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1620, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/li/anaconda3/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: connection to server at "ep-cold-cherry-a4g2g059.us-east-1.aws.neon.tech" (2600:1f18:240c:544d:621b:957c:81:5e5b), port 5432 failed: ERROR:  You've exceeded the rate limit. Please wait a moment and try again.

ERROR 2025-05-16 16:25:31,254 basehttp "GET / HTTP/1.1" 500 174096
WARNING 2025-05-16 16:25:59,930 base Session data corrupted
INFO 2025-05-16 16:26:01,637 basehttp "GET / HTTP/1.1" 200 41291
WARNING 2025-05-16 16:26:15,652 base Session data corrupted
INFO 2025-05-16 16:26:17,278 basehttp "GET / HTTP/1.1" 200 41251
WARNING 2025-05-16 16:31:50,751 base Session data corrupted
INFO 2025-05-16 16:31:52,548 basehttp "GET / HTTP/1.1" 200 42482
INFO 2025-05-16 16:31:53,140 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
WARNING 2025-05-16 16:32:30,442 base Session data corrupted
INFO 2025-05-16 16:32:32,187 basehttp "GET / HTTP/1.1" 200 43683
WARNING 2025-05-16 16:36:04,569 base Session data corrupted
INFO 2025-05-16 16:36:06,207 basehttp "GET / HTTP/1.1" 200 45890
WARNING 2025-05-16 16:36:16,969 base Session data corrupted
INFO 2025-05-16 16:36:18,628 basehttp "GET / HTTP/1.1" 200 45909
WARNING 2025-05-16 16:37:38,075 base Session data corrupted
INFO 2025-05-16 16:37:39,704 basehttp "GET / HTTP/1.1" 200 45995
INFO 2025-05-16 16:37:39,790 basehttp "GET /static/images/logo.png HTTP/1.1" 304 0
INFO 2025-05-16 16:40:32,352 autoreload Watching for file changes with StatReloader
INFO 2025-05-16 16:42:54,914 autoreload Watching for file changes with StatReloader
INFO 2025-05-17 08:49:54,943 autoreload Watching for file changes with StatReloader
INFO 2025-05-17 08:49:56,771 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-05-17 08:49:57,085 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-05-17 08:49:57,085 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-05-17 08:49:58,103 environment [ENV] 当前运行环境: development
INFO 2025-05-17 08:49:58,103 environment [ENV] 当前运行环境: development
INFO 2025-05-17 08:50:00,648 basehttp "GET / HTTP/1.1" 200 41223
INFO 2025-05-17 08:50:01,479 basehttp "GET /static/css/styles.css HTTP/1.1" 200 16527
INFO 2025-05-17 08:50:01,825 basehttp "GET /static/images/logo.png HTTP/1.1" 200 2687817
INFO 2025-05-17 09:06:44,326 autoreload Watching for file changes with StatReloader
INFO 2025-05-17 09:06:47,756 environment [ENV] 当前运行环境: development
INFO 2025-05-17 09:06:47,756 environment [ENV] 当前运行环境: development
INFO 2025-05-17 09:09:23,624 basehttp "GET / HTTP/1.1" 200 41401
INFO 2025-05-17 09:09:23,956 basehttp "GET /static/images/logo.png HTTP/1.1" 200 2687817
INFO 2025-05-17 09:10:08,409 basehttp "GET /locations/ HTTP/1.1" 200 10872
INFO 2025-05-17 09:10:17,427 basehttp "GET / HTTP/1.1" 200 41390
INFO 2025-05-17 09:23:32,054 autoreload Watching for file changes with StatReloader
INFO 2025-05-17 09:23:34,740 environment [ENV] 当前运行环境: development
INFO 2025-05-17 09:23:34,740 environment [ENV] 当前运行环境: development
INFO 2025-05-17 09:23:43,271 basehttp "GET / HTTP/1.1" 200 41153
